In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as spstats
import sklearn.preprocessing
pd.set_option('display.max_columns', None)  
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', -1)

from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction import FeatureHasher
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import KBinsDiscretizer

import pickle

%matplotlib inline

In [2]:
class PatientData:
    def __init__(self, file, **kwargs):
        self.file = file
        self.df = pd.read_csv(file, sep=kwargs['sep'])
    
    
    def getFile(self, **kwargs):
        return self.file
    
    
    def plotData(self,plottype, **kwargs):
        pass
    
    
    def get_data_frame(self):
        return self.df
    
    
    def add_column_df(self, column_name, feature_arr, new_column_name='-Transformation'):
        #feature_arr_T = feature_arr.transpose()
        #[self.df.insert(loc=df.columns.get_loc(column_name)+1+i, column=column_name[0:2]+str(i), value=new_col) 
                                                #for i, new_col in zip(range(len(feature_arr_T)), feature_arr_T)]
        self.df.insert(loc=self.df.columns.get_loc(column_name)+1, column=column_name+new_column_name, value=feature_arr.tolist())
        #self.df = self.df.assign(e=feature_arr)
        
    
    def show_dataframe(self, n=5):
        display(self.df.head(n))

In [3]:
#Discription of Data

pdata_disc = PatientData('../../lungpatientdata/Transformation_v2_24May/dataset_description.csv', sep='\t')
pdf_disc = pdata_disc.get_data_frame() 
pdf_disc.shape
cols = pdf_disc.columns
arg_cols_list = []
tmp = []
for col in cols:
    tmp.append(col)
    if 'Transformed' in col:
        arg_cols_list.append(tmp)
        tmp=[]
for mdf in arg_cols_list:
    display(pdf_disc[mdf].head(1))

   Age Transformed age
0  53   [0 1 0 0]

     Gender Transformed gender
0  C0025266  [1 0]

  Tumor_Type               Transformed Tumor_type
0  C0001418   [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]

  Surv_month Transformed_surv_month
0  former     [1 0 0 0]

   Chemotherapy Transformed chemotherapy
0  True          [1 0]

     Tki Transformed Tki
0  False  [0 1]

   Immunotherapy Transformed Immunotherapy
0  False          [0 1]

   Antiangiogenic Transformed Antiangiogenic
0  False           [0 1]

   Radiationtherapy Transformed Radiationtherapy
0  True              [1 0]

   Surgery Transformed Surgery
0  False    [0 1]

   Familial antecedent Transformed Familial_antecedent
0  True                 [1 0]

   Systemic Progression Transformed Systemic Progression
0  False                 [0 1]

   Local Progression Transformed Local Progression
0  False              [0 1]

   Brain Metastasis Transformed Brain Metastasis
0  False             [0 1]

,Chemoterapy List,Universe of chemotherapy,Transformed Chemoterapy List
0,"['C0008838', 'C0210657', 'C0246415']","['C0015133', 'C0008838', 'C0079083', 'C0078257', 'C0210657', 'C0246415', 'C0045093', 'C0144576']","[0, 1, 0, 0, 1, 1, 0, 0]"

,Familial antecedent List,Universe of familial antecedent,Transformed Familial antecedent List
0,['C0026591'],"['C0337578', 'C0015671', 'C1273524', 'C0337576', 'C0011011', 'C1273523', 'C3844805', 'C0080103', 'C1273525', 'C0337582', 'C0337527', 'C0015576', 'C0337514', 'C1273522', 'C0337581', 'C0337577', 'C0337579', 'C0026591', 'C0037047']","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]"

,Immunotherapy List,Universe of Immunotherapy,Transformed Immunotherapy List
0,[],"['C3658706', 'C1367202', 'C3657270']","[0, 0, 0]"

,Tki List,Universe of Tki,Transformed Tki List
0,[],"['C2974289', 'C4058811', 'C3853921', 'C3896906', 'C1135135', 'C3818721', 'C1122962', 'C2987648']","[0, 0, 0, 0, 0, 0, 0, 0]"

,Comorbidities List,Universe of Comorbidities,Transformed Comorbidities List
0,"['C0030193', 'C0231857']","['C0263236', 'C0242339', 'C0042075', 'C0035508', 'C0740394', 'C0149871', 'C0024117', 'C0030193', 'C0497156', 'C0013404', 'C0020676', 'C0011849', 'C0034067', 'C0020538', 'C0002871', 'C0010200', 'C0013604', 'C0919930', 'C0006318', 'C0231857', 'C0018799', 'C0020443']","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]"

,Drugs List,Universe of Drugs,Transformed Drugs List
0,['Antibiotic'],"['Steroid', 'Antiemetic', 'Anticoagulant', 'Antihyperuricemic', 'Gastric_protector', 'Benzodiazepine', 'Other', 'Antihypertensive', 'Analgesic', 'Diuretic', 'Antibiotic', 'Pain_killer', 'Dyslipidemic', 'Bronchodilator', 'Antidiabetic']","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]"

,Non_oncologycal_treat List,Universe of Non_oncologycal_treat,Transformed Non_oncologycal_treat List
0,['C0007546'],"['C0012586', 'C0024002', 'C0026056', 'C0286651', 'C0020852', 'C0014025', 'C0025853', 'C0052796', 'C0021641', 'C0011777', 'C0051696', 'C0030049', 'C0025815', 'C0008809', 'C0772505', 'C0001617', 'C0002771', 'C0020740', 'C0025598', 'C0028978', 'C0206460', 'C0007561', 'C0065185', 'C0026549', 'C0016860', 'C0006213', 'C0040610', 'C0007546', 'C0074554', 'C0003232', 'C0001927', 'C0004147', 'C0019134', 'C0000970', 'C0013136', 'C0282386', 'C0002144', 'C0034665', 'C0002645', 'C0073631', 'C0015846', 'C0061851', 'C0032952']","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

,Biopsy List,Universe of Biopsy,Transformed Biopsy List
0,[],"{'egfr_l861q', 'egfr_l858r', 'egfr_del19', 'egfr_t790m', 'egfr_g719x', 'egfr_ins20', 'unknown'}","[0, 0, 0, 0, 0, 0, 0]"

,Perform_status List,Universe of Perform_status,Transformed Perform_status
0,1.0,"['0', '1', '2', '3', '4', '5']",[0 1 0 0 0 0]

,Stage List,Universe of Stage,Transformed Stage
0,C0441772,"['C0441766', 'C0441767', 'C0441771', 'C0441772']",[0 0 0 1]

,Toxicities List,Universe of Toxicities,Transformed toxicities
0,"['C0004093', 'C0004093', 'C0004093', 'C0020517', 'C0004093', 'C0027497', 'C0042963', 'C0333355', 'C0027497', 'C0333355', 'C0333355', 'C0333355', 'C0333355', 'C0333355', 'C0027497', 'C0004093', 'C0232462', 'C0027497', 'C0333355', 'C0333355', 'C0020517', 'C0027497', 'C0020517', 'C2242708', 'C0232462', 'C0002871', 'C2242708', 'C0232462', 'C0002871', 'C2242708', 'C0232462', 'C0002871', 'C2242708', 'C0232462', 'C0002871', 'C0019158', 'C2242708', 'C0232462', 'C0027497', 'C0002871', 'C0019158', 'C2242708', 'C0232462', 'C0042963', 'C0002871', 'C2242708', 'C0002871', 'C2242708', 'C0027497', 'C0002871', 'C2242708', 'C0002871', 'C2242708', 'C0002871', 'C2242708']","['C0232462', 'C0035078', 'C0858733', 'C0002170', 'C0009319', 'C0038363', 'C0001403', 'C0001623', 'C0033774', 'C2363731', 'C0011053', 'C0026848', 'C0015230', 'C0042963', 'C0019158', 'C0032285', 'C0746883', 'C0020517', 'C0027697', 'C0009763', 'C0027947', 'C2242708', 'C0013378', 'C0027497', 'C0002792', 'C0011603', 'C0270994', 'C0010481', 'C0030305', 'C0020676', 'C0333355', 'C0438717', 'C0004093', 'C0332601', 'C0011991', 'C0342409', 'C2364111', 'C0019080', 'C0235032', 'C0042900', 'C0002871', 'C0020433', 'C0040034', 'C0235280', 'C0002594', 'C0162834', 'C1384666', 'C0003123', 'C0235378', 'C0599918', 'C0014356', 'C0020550']","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

In [4]:
# Transformed LCPatientData 

pdata = PatientData('../../lungpatientdata/Transformation_v3/dataset_LCPatient.csv', sep=',')
pdata.show_dataframe()
pdf = pdata.get_data_frame() 
pdf.columns

,patient_id,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168
0,1003706,1,0,0,1,0,0,1,0,0,1,0,1,1,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0
1,1007602,1,0,0,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0
2,1013426,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
3,1015121,1,0,0,1,0,0,1,0,0,1,1,0,1,0,0,1,1,0,1,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1
4,1019115,0,1,0,1,0,0,0,1,0,1,0,1,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1

Index(['patient_id', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       ...
       '159', '160', '161', '162', '163', '164', '165', '166', '167', '168'],
      dtype='object', length=170)

In [5]:
# LCPatientData_Label
pdataLabel = PatientData('../../lungpatientdata/patients.csv', sep=',')
pdataLabel.show_dataframe()
display(pdataLabel.get_data_frame().describe(include='all'))

pdf_label = pdataLabel.get_data_frame()[['patient_id','survivalMonths']]
pdf_label.head(5)

,patient_id,gender,diagnosisDate,tumorType,stageAtDiagnosis,ageAtDiagnosis,performanceStatusAtDiagnosis,smoker,biomarkers,bioEgfr,bioAlk,bioRos1,chemotherapy,tki,immunotherapy,antiangiogenic,radiationtherapy,surgery,familialAntecedents,systemicProgression,localProgression,brainMetastasis,survivalMonths
0,1003706,C0025266,2017-04-03,C0001418,C0441772,53,1.0,former,False,False,False,False,True,False,False,False,True,False,True,False,False,False,4
1,1007602,C0025266,2016-02-23,C0007097,C0441772,70,1.0,current,False,False,False,False,True,False,False,False,True,False,True,False,False,True,2
2,1013426,C0025266,2014-03-24,C0152013,C0441772,48,0.0,no,True,True,False,False,False,True,False,False,True,False,False,False,False,False,12
3,1013702,C0043210,2016-03-03,C0152013,C0441772,76,2.0,current,False,False,False,False,True,False,False,False,True,False,False,False,False,False,0
4,1015121,C0025266,2015-08-06,C0152013,C0441772,55,0.0,former,False,False,False,False,True,False,True,False,True,True,True,False,False,False,15

,patient_id,gender,diagnosisDate,tumorType,stageAtDiagnosis,ageAtDiagnosis,performanceStatusAtDiagnosis,smoker,biomarkers,bioEgfr,bioAlk,bioRos1,chemotherapy,tki,immunotherapy,antiangiogenic,radiationtherapy,surgery,familialAntecedents,systemicProgression,localProgression,brainMetastasis,survivalMonths
count,9.390000e+02,939,939,939,939,939.000000,732.000000,939,939,939,939,939,939,939,939,939,939,939,939,939,939,939,939.000000
unique,NaN,2,751,17,4,NaN,NaN,4,2,2,2,1,2,2,2,2,2,2,2,2,2,2,NaN
top,NaN,C0025266,2016-11-18,C0152013,C0441772,NaN,NaN,former,False,False,False,False,True,False,False,False,True,True,True,False,False,False,NaN
freq,NaN,663,5,183,526,NaN,NaN,695,821,848,912,939,655,823,818,916,615,488,516,769,864,744,NaN
mean,1.310331e+06,NaN,NaN,NaN,NaN,65.785942,0.655738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.733759
std,9.707625e+05,NaN,NaN,NaN,NaN,9.296007,0.837923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.706415
min,3.877000e+03,NaN,NaN,NaN,NaN,30.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,5.101020e+05,NaN,NaN,NaN,NaN,59.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000
50%,1.007602e+06,NaN,NaN,NaN,NaN,66.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000
75%,2.463002e+06,NaN,NaN,NaN,NaN,72.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000
max,2.815387e+06,NaN,NaN,NaN,NaN,89.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,263.000000

   patient_id  survivalMonths
0  1003706     4
1  1007602     2
2  1013426     12
3  1013702     0
4  1015121     15

In [6]:
# Regression problem not considering survival month labels
    
# Merge dataframe based on id
pdf_surmon = pd.merge(pdf, pdf_label, on=['patient_id'] )
pdf_surmon_cols = pdf_surmon.columns.tolist()
pdf_data = pdf_surmon[pdf_surmon_cols[0:1] + pdf_surmon_cols[-1:] + pdf_surmon_cols[1:-1]]
display (pdf_data[pdf_data['patient_id']==974679]['survivalMonths'], pdf_label[pdf_label['patient_id']==974679]['survivalMonths'])
display(pdf_data.head(5))
display(pdf_data.describe())


# Dumping modified data
target = pdf_data['survivalMonths'].values
data = pdf_data.iloc[:,2:].values
patient_data = {'data':data, 'target':target}
pickle.dump( patient_data, open( "../../lungpatientdata/Transformation_v3/patient_data.pkl", "wb"))
#pickle.load(open('../../lungpatientdata/Transformation_v3/patient_data.pkl', "rb"))

Series([], Name: survivalMonths, dtype: int64)

932    70
Name: survivalMonths, dtype: int64

,patient_id,survivalMonths,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168
0,1003706,4,1,0,0,1,0,0,1,0,0,1,0,1,1,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0
1,1007602,2,1,0,0,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0
2,1013426,12,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
3,1015121,15,1,0,0,1,0,0,1,0,0,1,1,0,1,0,0,1,1,0,1,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1
4,1019115,19,0,1,0,1,0,0,0,1,0,1,0,1,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1

,patient_id,survivalMonths,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168
count,8.200000e+02,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.0,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.0,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.0,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.0,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.0,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000,820.0,820.000000,820.000000,820.000000,820.000000,820.000000,820.000000
mean,1.334450e+06,16.817073,0.715854,0.284146,0.008537,0.741463,0.098780,0.151220,0.657317,0.342683,0.019512,0.980488,0.504878,0.495122,0.557317,0.442683,0.208537,0.791463,0.264634,0.176829,0.308537,0.096341,0.515854,0.214634,0.058537,0.191463,0.112195,0.042683,0.029268,0.031707,0.008537,0.047561,0.043902,0.0,0.024390,0.020732,0.009756,0.024390,0.037805,0.214634,0.046341,0.092683,0.041463,0.121951,0.062195,0.258537,0.057317,0.182927,0.137805,0.025610,0.017073,0.030488,0.052439,0.169512,0.120732,0.080488,0.064634,0.492683,0.213415,0.002439,0.001220,0.028049,0.062195,0.002439,0.012195,0.018293,0.373171,0.291463,0.063415,0.014634,0.039024,0.001220,0.031707,0.013415,0.001220,0.0,0.053659,0.015854,0.014634,0.052439,0.004878,0.019512,0.013415,0.007317,0.014634,0.009756,0.042683,0.008537,0.0,0.065854,0.007317,0.013415,0.006098,0.001220,0.090244,0.006098,0.008537,0.002439,0.0,0.032927,0.024390,0.007317,0.045122,0.006098,0.018293,0.030488,0.117073,0.004878,0.001220,0.034146,0.010976,0.007317,0.021951,0.009756,0.030488,0.196341,0.143902,0.336585,0.323171,0.689024,0.397561,0.010976,0.007317,0.024390,0.391463,0.036585,0.003659,0.004878,0.030488,0.056098,0.032927,0.164634,0.017073,0.087805,0.260976,0.260976,0.046341,0.096341,0.041463,0.150000,0.050000,0.012195,0.001220,0.024390,0.153659,0.002439,0.008537,0.045122,0.0,0.142683,0.087805,0.007317,0.323171,0.595122,0.035366,0.009756,0.001220,0.039024,0.091463,0.031707,0.193902,0.004878,0.526829,0.008537,0.0,0.552439,0.017073,0.670732,0.026829,0.100000,0.339024
std,9.831137e+05,13.954337,0.451282,0.451282,0.092055,0.438098,0.298549,0.358481,0.474896,0.474896,0.138401,0.138401,0.500281,0.500281,0.497007,0.497007,0.406510,0.406510,0.441407,0.381757,0.462171,0.295239,0.500054,0.410819,0.234899,0.393693,0.315799,0.202265,0.168660,0.175327,0.092055,0.212965,0.205003,0.0,0.154352,0.142572,0.098350,0.154352,0.190840,0.410819,0.210352,0.290165,0.199481,0.327429,0.241657,0.438098,0.232589,0.386842,0.344905,0.158064,0.129623,0.172030,0.223047,0.375433,0.326014,0.272213,0.246029,0.500252,0.409968,0.049356,0.034922,0.165213,0.241657,0.049356,0.109823,0.134089,0.483942,0.454714,0.243856,0.120157,0.193771,0.034922,0.175327,0.115112,0.034922,0.0,0.225480,0.124985,0.120157,0.223047,0.069715,0.138401,0.115112,0.085278,0.120157,0.098350,0.202265,0.092055,0.0,0.248177,0.085278,0.115112,0.077896,0.034922,0.286706,0.077896,0.092055,0.049356,0.0,0.178554,0.154352,0.085278,0.207698,0.077896,0.134089,0.172030,0.321704,0.069715,0.034922,0.181716,0.104252,0.085278,0.146614,0.098350,0.172030,0.397472,0.351205,0.472830,0.467973,0.463175,0.489692,0.104252,0.085278,0.154352,0.488376,0.187856,0.060412,0.069715,0.172030,0.230250,0.178554,0.371076,0.129623,0.283184,0.439435,0.439435,0.210352,0.295239,0.199481,0.357289,0.218078,0.109823,0.034922,0.154352,0.360841,0.049356,0.092055,0.207698,0.0,0.349963,0.283184,0.085278,0.467973,0.491168,0.184815,0.098350,0.034922,0.193771,0.288443,0.175327,0.395595,0.069715,0.499584,0.092055,0.0,0.497546,0.129623,0.470234,0.161683,0.300183,0.473667
min,3.877000e+03,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.989232e+05,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.042019e+06,13.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,2.492115e+06,25.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,2.812882e+06,59.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000