In [4]:
import pandas as pd
import numpy as np
import scipy.stats as spstats
import matplotlib.pyplot as plt
from feature_transformation_cls import FeatureTransform

from ast import literal_eval

pd.set_option('display.max_columns', None)  
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', -1)


%matplotlib inline

In [15]:
folder_path = '../../../datalcdem/data/optima/dementia_18July/class_mild_mod_sev/'
patient_df = pd.read_csv(folder_path+'patients_new.csv')
print ('Patient Column size:', len(patient_df.columns))
print (patient_df.shape, len(patient_df.columns), patient_df.columns)
display(patient_df.head(10))

#extract episode data and calculate duration
patient_episode_date_df = patient_df[['patient_id'] + [col for col in patient_df.columns if 'EPISODE_DATE' in col]]
display(patient_episode_date_df.head(10))

def calculate_duration_btw_dates(df, col1, col2 ):
    return ((pd.to_datetime(df[col1]) - pd.to_datetime(df[col2]))/  np.timedelta64(1, 'D'))/365.25

patient_episode_date_duration_df = patient_episode_date_df[['patient_id']].copy()
for episode_date_col in patient_episode_date_df.columns[2:]:
    patient_episode_date_duration_df[episode_date_col+'-EPISODE_DATE(year)'] = calculate_duration_btw_dates(patient_episode_date_df, episode_date_col, 'EPISODE_DATE')
display(patient_episode_date_duration_df.head(10))


# saving file to csv file and drop EPISODE_DATE
patient_df.drop(columns=[col for col in patient_df.columns if 'EPISODE_DATE' in col], inplace=True)
display(patient_df.head(10))
patient_df.to_csv(folder_path+ 'patient_new_df.csv', index=False)

Patient Column size: 59
(820, 59) 59 Index(['patient_id', 'gender', 'dementia', 'smoker', 'alcohol', 'education',
       'bmi', 'weight', 'apoe', 'EPISODE_DATE', 'Comorbidity_cui',
       'Medication_cui', 'Age At Episode', 'CAMDEX SCORES: MINI MENTAL SCORE',
       'EPISODE_DATE_1', 'Comorbidity_cui_1', 'Medication_cui_1',
       'Age At Episode_1', 'CAMDEX SCORES: MINI MENTAL SCORE_1',
       'EPISODE_DATE_2', 'Comorbidity_cui_2', 'Medication_cui_2',
       'Age At Episode_2', 'CAMDEX SCORES: MINI MENTAL SCORE_2',
       'EPISODE_DATE_3', 'Comorbidity_cui_3', 'Medication_cui_3',
       'Age At Episode_3', 'CAMDEX SCORES: MINI MENTAL SCORE_3',
       'EPISODE_DATE_4', 'Comorbidity_cui_4', 'Medication_cui_4',
       'Age At Episode_4', 'CAMDEX SCORES: MINI MENTAL SCORE_4',
       'EPISODE_DATE_5', 'Comorbidity_cui_5', 'Medication_cui_5',
       'Age At Episode_5', 'CAMDEX SCORES: MINI MENTAL SCORE_5',
       'EPISODE_DATE_6', 'Comorbidity_cui_6', 'Medication_cui_6',
       'Age At Episode_6', 'CAMDEX SCORES: MINI MENTAL SCORE_6',
       'EPISODE_DATE_7', 'Comorbidity_cui_7', 'Medication_cui_7',
       'Age At Episode_7', 'CAMDEX SCORES: MINI MENTAL SCORE_7',
       'EPISODE_DATE_8', 'Comorbidity_cui_8', 'Medication_cui_8',
       'Age At Episode_8', 'CAMDEX SCORES: MINI MENTAL SCORE_8',
       'EPISODE_DATE_9', 'Comorbidity_cui_9', 'Medication_cui_9',
       'Age At Episode_9', 'CAMDEX SCORES: MINI MENTAL SCORE_9'],
      dtype='object')

,patient_id,gender,dementia,smoker,alcohol,education,bmi,weight,apoe,EPISODE_DATE,Comorbidity_cui,Medication_cui,Age At Episode,CAMDEX SCORES: MINI MENTAL SCORE,EPISODE_DATE_1,Comorbidity_cui_1,Medication_cui_1,Age At Episode_1,CAMDEX SCORES: MINI MENTAL SCORE_1,EPISODE_DATE_2,Comorbidity_cui_2,Medication_cui_2,Age At Episode_2,CAMDEX SCORES: MINI MENTAL SCORE_2,EPISODE_DATE_3,Comorbidity_cui_3,Medication_cui_3,Age At Episode_3,CAMDEX SCORES: MINI MENTAL SCORE_3,EPISODE_DATE_4,Comorbidity_cui_4,Medication_cui_4,Age At Episode_4,CAMDEX SCORES: MINI MENTAL SCORE_4,EPISODE_DATE_5,Comorbidity_cui_5,Medication_cui_5,Age At Episode_5,CAMDEX SCORES: MINI MENTAL SCORE_5,EPISODE_DATE_6,Comorbidity_cui_6,Medication_cui_6,Age At Episode_6,CAMDEX SCORES: MINI MENTAL SCORE_6,EPISODE_DATE_7,Comorbidity_cui_7,Medication_cui_7,Age At Episode_7,CAMDEX SCORES: MINI MENTAL SCORE_7,EPISODE_DATE_8,Comorbidity_cui_8,Medication_cui_8,Age At Episode_8,CAMDEX SCORES: MINI MENTAL SCORE_8,EPISODE_DATE_9,Comorbidity_cui_9,Medication_cui_9,Age At Episode_9,CAMDEX SCORES: MINI MENTAL SCORE_9
0,1,Male,False,smoker,mild_drinking,medium,28.0,81.0,E3E3,1998-01-13,NaN,['C0004147'],71,30.0,1998-12-14,NaN,['C0004147'],72.0,NaN,2000-01-20,NaN,['C0004147'],73.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14,Female,False,no_smoker,mild_drinking,medium,19.0,48.0,E3E4,1992-04-28,['C0012546'],NaN,81,28.0,1994-04-14,NaN,['C0004147'],83.0,30.0,1995-04-27,NaN,['C0004147'],84.0,30.0,1996-03-18,NaN,['C0004147'],85.0,29.0,1997-03-27,NaN,"['C0004147', 'C3540037']",86.0,30.0,1998-04-16,NaN,"['C0017631', 'C0004147', 'C0012373']",87.0,30.0,1999-03-19,"['C0011847', 'C0018801', 'C0007787']","['C0017631', 'C0004147']",88.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16,Male,False,no_smoker,extreme_drinking,higher,NaN,NaN,E3E4,1991-07-15,"['C0586324', 'C0007787']",NaN,78,28.0,1993-09-22,NaN,['C0591154'],81.0,28.0,1994-09-05,NaN,['C0591154'],82.0,25.0,1995-07-03,NaN,['C0000970'],82.0,24.0,1996-10-21,NaN,"['C0591205', 'C0003663', 'C0020316']",84.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19,Male,True,smoker,extreme_drinking,higher,NaN,NaN,E3E4,1990-09-17,['C0011847'],['C0040374'],57,15.0,1991-04-12,NaN,['C0040374'],58.0,5.0,1991-11-12,['C0011847'],['C0040374'],58.0,7.0,1992-05-20,NaN,['C0040374'],59.0,6.0,1992-11-10,['C0011847'],['C0040374'],59.0,0.0,1993-05-19,NaN,['C0040374'],60.0,0.0,1993-11-23,['C0011847'],['C0040374'],60.0,0.0,1994-05-23,NaN,['C0040374'],61.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,36,Female,False,smoker,mild_drinking,higher,23.0,54.0,E3E4,2004-09-06,NaN,['C2346927'],84,-1.0,2005-03-04,NaN,['C2346927'],85.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,47,Male,False,smoker,extreme_drinking,medium,NaN,NaN,E3E4,1989-05-25,NaN,"['C0065502', 'C2346927', 'C0600062']",81,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,54,Female,False,no_smoker,mild_drinking,higher,26.0,76.0,E3E3,1998-05-19,['C0026267'],NaN,61,26.0,2004-11-08,NaN,['C0004147'],67.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,60,Male,False,smoker,extreme_drinking,NaN,NaN,NaN,E3E4,1994-03-03,NaN,['C0039943'],68,13.0,1994-12-12,NaN,['C0039943'],69.0,15.0,1995-04-28,NaN,['C0039943'],69.0,20.0,1995-10-26,NaN,['C0039943'],69.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,93,Female,True,no_smoker,mild_drinking,NaN,29.0,73.0,E3E3,2004-09-23,NaN,['C2346927'],81,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,94,Male,True,smoker,mild_drinking,NaN,32.0,91.0,E3E3,1998-05-01,NaN,"['C0000970', 'C2346927']",75,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,patient_id,EPISODE_DATE,EPISODE_DATE_1,EPISODE_DATE_2,EPISODE_DATE_3,EPISODE_DATE_4,EPISODE_DATE_5,EPISODE_DATE_6,EPISODE_DATE_7,EPISODE_DATE_8,EPISODE_DATE_9
0,1,1998-01-13,1998-12-14,2000-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14,1992-04-28,1994-04-14,1995-04-27,1996-03-18,1997-03-27,1998-04-16,1999-03-19,NaN,NaN,NaN
2,16,1991-07-15,1993-09-22,1994-09-05,1995-07-03,1996-10-21,NaN,NaN,NaN,NaN,NaN
3,19,1990-09-17,1991-04-12,1991-11-12,1992-05-20,1992-11-10,1993-05-19,1993-11-23,1994-05-23,NaN,NaN
4,36,2004-09-06,2005-03-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,47,1989-05-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,54,1998-05-19,2004-11-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,60,1994-03-03,1994-12-12,1995-04-28,1995-10-26,NaN,NaN,NaN,NaN,NaN,NaN
8,93,2004-09-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,94,1998-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,patient_id,EPISODE_DATE_1-EPISODE_DATE(year),EPISODE_DATE_2-EPISODE_DATE(year),EPISODE_DATE_3-EPISODE_DATE(year),EPISODE_DATE_4-EPISODE_DATE(year),EPISODE_DATE_5-EPISODE_DATE(year),EPISODE_DATE_6-EPISODE_DATE(year),EPISODE_DATE_7-EPISODE_DATE(year),EPISODE_DATE_8-EPISODE_DATE(year),EPISODE_DATE_9-EPISODE_DATE(year)
0,1,0.917180,2.017796,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14,1.960301,2.995209,3.887748,4.911704,5.965777,6.888433,NaN,NaN,NaN
2,16,2.190281,3.143053,3.967146,5.270363,NaN,NaN,NaN,NaN,NaN
3,19,0.566735,1.152635,1.672827,2.149213,2.669405,3.184120,3.679671,NaN,NaN
4,36,0.490075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,54,6.475017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,60,0.777550,1.152635,1.648186,NaN,NaN,NaN,NaN,NaN,NaN
8,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,patient_id,gender,dementia,smoker,alcohol,education,bmi,weight,apoe,Comorbidity_cui,Medication_cui,Age At Episode,CAMDEX SCORES: MINI MENTAL SCORE,Comorbidity_cui_1,Medication_cui_1,Age At Episode_1,CAMDEX SCORES: MINI MENTAL SCORE_1,Comorbidity_cui_2,Medication_cui_2,Age At Episode_2,CAMDEX SCORES: MINI MENTAL SCORE_2,Comorbidity_cui_3,Medication_cui_3,Age At Episode_3,CAMDEX SCORES: MINI MENTAL SCORE_3,Comorbidity_cui_4,Medication_cui_4,Age At Episode_4,CAMDEX SCORES: MINI MENTAL SCORE_4,Comorbidity_cui_5,Medication_cui_5,Age At Episode_5,CAMDEX SCORES: MINI MENTAL SCORE_5,Comorbidity_cui_6,Medication_cui_6,Age At Episode_6,CAMDEX SCORES: MINI MENTAL SCORE_6,Comorbidity_cui_7,Medication_cui_7,Age At Episode_7,CAMDEX SCORES: MINI MENTAL SCORE_7,Comorbidity_cui_8,Medication_cui_8,Age At Episode_8,CAMDEX SCORES: MINI MENTAL SCORE_8,Comorbidity_cui_9,Medication_cui_9,Age At Episode_9,CAMDEX SCORES: MINI MENTAL SCORE_9
0,1,Male,False,smoker,mild_drinking,medium,28.0,81.0,E3E3,NaN,['C0004147'],71,30.0,NaN,['C0004147'],72.0,NaN,NaN,['C0004147'],73.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14,Female,False,no_smoker,mild_drinking,medium,19.0,48.0,E3E4,['C0012546'],NaN,81,28.0,NaN,['C0004147'],83.0,30.0,NaN,['C0004147'],84.0,30.0,NaN,['C0004147'],85.0,29.0,NaN,"['C0004147', 'C3540037']",86.0,30.0,NaN,"['C0017631', 'C0004147', 'C0012373']",87.0,30.0,"['C0011847', 'C0018801', 'C0007787']","['C0017631', 'C0004147']",88.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16,Male,False,no_smoker,extreme_drinking,higher,NaN,NaN,E3E4,"['C0586324', 'C0007787']",NaN,78,28.0,NaN,['C0591154'],81.0,28.0,NaN,['C0591154'],82.0,25.0,NaN,['C0000970'],82.0,24.0,NaN,"['C0591205', 'C0003663', 'C0020316']",84.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19,Male,True,smoker,extreme_drinking,higher,NaN,NaN,E3E4,['C0011847'],['C0040374'],57,15.0,NaN,['C0040374'],58.0,5.0,['C0011847'],['C0040374'],58.0,7.0,NaN,['C0040374'],59.0,6.0,['C0011847'],['C0040374'],59.0,0.0,NaN,['C0040374'],60.0,0.0,['C0011847'],['C0040374'],60.0,0.0,NaN,['C0040374'],61.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,36,Female,False,smoker,mild_drinking,higher,23.0,54.0,E3E4,NaN,['C2346927'],84,-1.0,NaN,['C2346927'],85.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,47,Male,False,smoker,extreme_drinking,medium,NaN,NaN,E3E4,NaN,"['C0065502', 'C2346927', 'C0600062']",81,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,54,Female,False,no_smoker,mild_drinking,higher,26.0,76.0,E3E3,['C0026267'],NaN,61,26.0,NaN,['C0004147'],67.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,60,Male,False,smoker,extreme_drinking,NaN,NaN,NaN,E3E4,NaN,['C0039943'],68,13.0,NaN,['C0039943'],69.0,15.0,NaN,['C0039943'],69.0,20.0,NaN,['C0039943'],69.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,93,Female,True,no_smoker,mild_drinking,NaN,29.0,73.0,E3E3,NaN,['C2346927'],81,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,94,Male,True,smoker,mild_drinking,NaN,32.0,91.0,E3E3,NaN,"['C0000970', 'C2346927']",75,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
display(patient_df.columns)

columns_nominal = ['gender', 'dementia', 'smoker', 'alcohol', 'education', 'apoe'] 

# Not needed for nominal class this 'mmseInicialDiscretized', 'mmseFinalDiscretized']

columns_bins = ['bmi', 'weight'] + [col for col in patient_df.columns if 'Age At Episode' in col]
                
# not needed for bin class 'mmseInicial', 'mmseFinal'

columns_list = [col for col in patient_df.columns if '_cui' in col]

print (columns_list, columns_bins)

columns_for_transformation = [columns_nominal, columns_bins, columns_list]
    
# epDateInicial,epDateFinal,epDateToSevereData,epDateToMildData, epDateToModerateData -- Column are not under obervation

Index(['patient_id', 'gender', 'dementia', 'smoker', 'alcohol', 'education',
       'bmi', 'weight', 'apoe', 'Comorbidity_cui', 'Medication_cui',
       'Age At Episode', 'CAMDEX SCORES: MINI MENTAL SCORE',
       'Comorbidity_cui_1', 'Medication_cui_1', 'Age At Episode_1',
       'CAMDEX SCORES: MINI MENTAL SCORE_1', 'Comorbidity_cui_2',
       'Medication_cui_2', 'Age At Episode_2',
       'CAMDEX SCORES: MINI MENTAL SCORE_2', 'Comorbidity_cui_3',
       'Medication_cui_3', 'Age At Episode_3',
       'CAMDEX SCORES: MINI MENTAL SCORE_3', 'Comorbidity_cui_4',
       'Medication_cui_4', 'Age At Episode_4',
       'CAMDEX SCORES: MINI MENTAL SCORE_4', 'Comorbidity_cui_5',
       'Medication_cui_5', 'Age At Episode_5',
       'CAMDEX SCORES: MINI MENTAL SCORE_5', 'Comorbidity_cui_6',
       'Medication_cui_6', 'Age At Episode_6',
       'CAMDEX SCORES: MINI MENTAL SCORE_6', 'Comorbidity_cui_7',
       'Medication_cui_7', 'Age At Episode_7',
       'CAMDEX SCORES: MINI MENTAL SCORE_7', 'Comorbidity_cui_8',
       'Medication_cui_8', 'Age At Episode_8',
       'CAMDEX SCORES: MINI MENTAL SCORE_8', 'Comorbidity_cui_9',
       'Medication_cui_9', 'Age At Episode_9',
       'CAMDEX SCORES: MINI MENTAL SCORE_9'],
      dtype='object')

['Comorbidity_cui', 'Medication_cui', 'Comorbidity_cui_1', 'Medication_cui_1', 'Comorbidity_cui_2', 'Medication_cui_2', 'Comorbidity_cui_3', 'Medication_cui_3', 'Comorbidity_cui_4', 'Medication_cui_4', 'Comorbidity_cui_5', 'Medication_cui_5', 'Comorbidity_cui_6', 'Medication_cui_6', 'Comorbidity_cui_7', 'Medication_cui_7', 'Comorbidity_cui_8', 'Medication_cui_8', 'Comorbidity_cui_9', 'Medication_cui_9'] ['bmi', 'weight', 'Age At Episode', 'Age At Episode_1', 'Age At Episode_2', 'Age At Episode_3', 'Age At Episode_4', 'Age At Episode_5', 'Age At Episode_6', 'Age At Episode_7', 'Age At Episode_8', 'Age At Episode_9']

In [ ]:
featuretransform = FeatureTransform(folder_path + 'patient_new_df.csv')
patient_df = featuretransform.get_data_frame()

# define class
patient_df['epDateFinal-epDateInicial(year)'] = ((pd.to_datetime(patient_df['epDateFinal']) - pd.to_datetime(patient_df['epDateInicial']))/  np.timedelta64(1, 'D'))/365.25
featuretransform.set_data_frame(patient_df)


# Drop columns After considering class with Slow, Normal, Fast conditions
patient_df['patient_class'] = 9
def calculate_class(patient_df, mmseInicialDiscretized, mmseFinalDiscretized, time1, time2, label):
    #return np.where((patient_df['mmseInicialDiscretized']==mmseInicialDiscretized) & (patient_df['mmseFinalDiscretized']==mmseFinalDiscretized) 
    #                & (patient_df['epDateFinal-epDateInicial(year)']>=time1) & (patient_df['epDateFinal-epDateInicial(year)']<time2), label, 9)  # largest value for class+1 = 3
    patient_df.loc[(patient_df['mmseInicialDiscretized']==mmseInicialDiscretized) & (patient_df['mmseFinalDiscretized']==mmseFinalDiscretized) 
              & (patient_df['epDateFinal-epDateInicial(year)']>=time1) & (patient_df['epDateFinal-epDateInicial(year)']<time2), 'patient_class'] = label

# normal, mild, moderate, severe
calculate_class(patient_df, 'mild', 'moderate', 0, 2, 0)
calculate_class(patient_df, 'mild', 'moderate', 2, 4, 1)
calculate_class(patient_df, 'mild', 'moderate', 4, max(patient_df['epDateFinal-epDateInicial(year)'])+1, 2)
calculate_class(patient_df, 'moderate', 'severe', 0, 3, 3)
calculate_class(patient_df, 'moderate', 'severe', 3, 5, 4)
calculate_class(patient_df, 'moderate', 'severe', 5, max(patient_df['epDateFinal-epDateInicial(year)'])+1, 5)
calculate_class(patient_df, 'mild', 'severe', 0, 5, 6)
calculate_class(patient_df, 'mild', 'severe', 5, 9, 7)
calculate_class(patient_df, 'mild', 'severe', 9, max(patient_df['epDateFinal-epDateInicial(year)'])+1, 8)
# drop columns Which has class
patient_df = patient_df[patient_df['patient_class']!=9]


'''# Drop columns After considering class Mild, Moderate adn Severe
patient_df['patient_class']= patient_df['mmseInicialDiscretized']
patient_df = patient_df[patient_df['patient_class']!='normal']
patient_df.replace(['mild', 'moderate', 'severe'], [0,1,2], inplace=True)'''


display(patient_df.head(10))
display(patient_df.describe(include='all'))

patient_df = patient_df.drop(labels=['mmseInicialDiscretized', 'mmseFinalDiscretized', 'mmseInicial', 'mmseFinal', 'epDateInicial',
                                     'epDateFinal', 'epDateToSevereData', 'epDateToMildData', 'epDateToModerateData', 'epDateFinal-epDateInicial(year)' ], axis=1)
patient_df.info()


# set patient_df
featuretransform.set_data_frame(patient_df)

# Nominal Transfromation
# featuretransform.apply_feature_transform(column_name='mmseFinalDiscretized', func_type='oneHot', data_type_func='nominal')
[featuretransform.apply_feature_transform(column_name=col, func_type='oneHot', data_type_func='nominal') for col in columns_nominal]



# Bins Transformation
#featuretransform.apply_feature_transform(column_name='mmseFinal', func_type='oneHot', data_type_func='bin', n_bins=5, encode='ordinal', strategy='quantile')
[featuretransform.apply_feature_transform(column_name=col, func_type='oneHot', data_type_func='bin', n_bins=5, encode='ordinal', strategy='quantile') for col in columns_bins]

# List Transformation
# classses
disorderName_cui_cls = list(featuretransform.extract_value_frm_list(patient_df['disorderName_cui'].dropna().apply(literal_eval).tolist()))
drugName_cui_cls = list(featuretransform.extract_value_frm_list(patient_df['drugName_cui'].dropna().apply(literal_eval).tolist()))
classeslist = [disorderName_cui_cls, drugName_cui_cls]
print (disorderName_cui_cls)
print (drugName_cui_cls)
#featuretransform.apply_feature_transform(column_name='drugName_cui', func_type='multiLabel', classes=drugName_cui_cls, data_type_func='ordinal')
[featuretransform.apply_feature_transform(column_name=col, func_type='multiLabel', classes=clss, data_type_func='ordinal') for col, clss in zip(columns_list, classeslist)]
featuretransform.show_dataframe()

# set patient_df
patient_df = featuretransform.get_data_frame()

In [ ]:
# save transformed data and dataset description
patient_df[[col for col in patient_df.columns.tolist() if '_TFV_' not in col]].to_csv(folder_path+'dataset_description.csv', index=False)

patient_df[['patient_id']+[col for col in patient_df.columns.tolist() if '_TFV_' in col]].to_csv(folder_path+'dataset_DementiaPatient.csv', index=False)

#print(patient_df_trans.info())
#patient_df_trans.head(10)